#!/bin/sh
set -e

# mount data partition
mount -o noatime /dev/mmcblk0p5 /run

for dir in etc root opt var/cache var/db var/lib; do
    mkdir -p /run/$dir
    mount --bind /run/$dir /$dir
done

# mount virtual filesystems
mount -t sysfs sysfs /sys
mount -t proc proc /proc

mkdir -p /dev/pts /dev/shm
mount -t devpts devpts /dev/pts
mount -t tmpfs shm /dev/shm

# mount memory mapped filesystems
mount -t tmpfs tmpfs /tmp
mount -t tmpfs tmpfs /run
mkdir -p /run/lock /run/log

# hand off to runit
exec /bin/runit
