#!/bin/sh
set -e

# mount virtual filesystems
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc

mkdir -p /dev/pts /dev/shm
mount -t devpts devpts /dev/pts
mount -t tmpfs shm /dev/shm

# mount root filesystem
mount -o noatime /dev/nvme0n1p1 /run

for dir in etc root opt var/cache var/db var/lib var/tmp; do
    mkdir -p /run/$dir
    mount --bind /run/$dir /$dir
done

# mount memory mapped filesystems
mount -t tmpfs tmpfs /tmp
mount -t tmpfs tmpfs /run
mkdir -p /run/lock /run/log

# hand off to runit
exec /bin/runit
